name: Integration tests

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
  # trigger on merge group as well (merge queue)
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest-16
    steps:
      - uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run e2e tests
        run: yarn e2e
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
